#!/bin/bash

chan=(
	http://46.40.5.99:8000/rtv1_720
	http://46.40.5.99:8000/rts1_320
	http://46.40.5.99:8000/rts2_320
	http://46.40.5.99:8000/pink_320
	http://46.40.5.99:8000/prvatv_320
	http://46.40.5.99:8000/b92_320
	http://46.40.5.99:8000/rtv1_320
	http://46.40.5.99:8000/rtv2_320
	http://46.40.5.99:8000/fox_320
	http://46.40.5.99:8000/foxlife_320
	http://46.40.5.99:8000/mtvadria_320
	http://46.40.5.99:8000/vh1_320
	http://46.40.5.99:8000/arena_1_320
	http://46.40.5.99:8000/arena_2_320
	http://46.40.5.99:8000/arena_3_320
	http://46.40.5.99:8000/arena_4_320
	http://46.40.5.99:8000/viasat_explorer_320
	http://46.40.5.99:8000/viasat_history_320
	http://46.40.5.99:8000/davinchi_320
	http://46.40.5.99:8000/ngce_320
	http://46.40.5.99:8000/viasat_nature_320
	http://46.40.5.99:8000/travel_320
	http://46.40.5.99:8000/mgm_320
	http://46.40.5.99:8000/disney_320
	http://46.40.5.99:8000/m1_hd_320
	http://46.40.5.99:8000/m2_hd_320
	http://46.40.5.99:8000/duna_hd_320
	http://46.40.5.99:8000/duna_world_hd_320
	http://46.40.5.99:8000/tv2_320
	http://46.40.5.99:8000/rtlklub_320
	http://46.40.5.99:8000/story4_320
	http://46.40.5.99:8000/stv1_320
	http://46.40.5.99:8000/markiza_320
	http://46.40.5.99:8000/rts1_720
	http://46.40.5.99:8000/rts2_720
	http://46.40.5.99:8000/pink_720
	http://46.40.5.99:8000/prvatv_720
	http://46.40.5.99:8000/b92_720
	http://46.40.5.99:8000/rtv1_720
	http://46.40.5.99:8000/rtv2_720
	http://46.40.5.99:8000/fox_720
	http://46.40.5.99:8000/foxlife_720
	http://46.40.5.99:8000/mtvadria_720
	http://46.40.5.99:8000/vh1_720
	http://46.40.5.99:8000/arena_1_720
	http://46.40.5.99:8000/arena_2_720
	http://46.40.5.99:8000/arena_3_720
	http://46.40.5.99:8000/arena_4_720
	http://46.40.5.99:8000/viasat_explorer_720
	http://46.40.5.99:8000/viasat_history_720
	http://46.40.5.99:8000/davinchi_720
	http://46.40.5.99:8000/ngce_720
	http://46.40.5.99:8000/viasat_nature_720
	http://46.40.5.99:8000/travel_720
	http://46.40.5.99:8000/mgm_720
	http://46.40.5.99:8000/disney_720
	http://46.40.5.99:8000/m1_hd_720
	http://46.40.5.99:8000/m2_hd_720
	http://46.40.5.99:8000/duna_hd_720
	http://46.40.5.99:8000/duna_world_hd_720
	http://46.40.5.99:8000/tv2_720
	http://46.40.5.99:8000/rtlklub_720
	http://46.40.5.99:8000/story4_720
	http://46.40.5.99:8000/stv1_720
	http://46.40.5.99:8000/markiza_720
)

problemFound=false

while true
do
	for item in ${chan[*]}
	do
		echo $item
		#ffmpeg -i $item -map 0:v -map 0:a:0 -af volumedetect -vf blackframe,mpdecimate=frac=1:hi=768 -t 00:00:05.00 -y -f flv out.flv 2> out.txt
		ffmpeg -i $item -map 0:v -map 0:a:0 -af volumedetect -filter_complex "smartblur=lr=5:cr=5[a];[a]mpdecimate=max=20:frac=1:hi=768[b];[b]blackframe" -t 00:00:05.00 -y -f flv out.flv 2> out.txt
		chan_result=$?
		echo "       Chan result:" $chan_result
		if [ "$chan_result" == "0" ]; then
			sound_lvl=$(cat out.txt | grep max_volume | cut -d" " -f5)
			echo "       Sound level:" $sound_lvl" dB"
			black_dur=$(cat out.txt | grep -c blackframe)
			echo "      Black frames:" $black_dur" fs"
			comp_lvl=$(ls out.flv -l | cut -d" " -f 5)
			echo " Compression level:" ${comp_lvl:0:(-3)}" tB"
			if [ $(echo $sound_lvl" < -45 " | bc -l) == "1" ]; then
				problemFound=true
				echo Suspected $item sound level too low - $sound_lvl " dB"
			fi
			if [ "$black_dur" -gt 100 ]; then
				problemFound=true
				echo Suspected $item too much black frames found - $black_dur " fs"
			fi
			if [ "$comp_lvl" -lt 100000 ]; then
				problemFound=true
				echo Suspected $item compression too low - $comp_lvl " tB"
			fi
		else
			problemFound=true
			echo Suspected $item produced open error
		fi
		if [ "$problemFound" = true ]; then
			problemFound=false
			#ffmpeg -i $item -map 0:v -map 0:a:0 -af volumedetect -vf blackframe,mpdecimate=frac=1:hi=768 -t 00:00:15.00 -y -f flv out.flv 2> out.txt
			ffmpeg -i $item -map 0:v -map 0:a:0 -af volumedetect -filter_complex "smartblur=lr=5:cr=5[a];[a]mpdecimate=max=20:frac=1:hi=768[b];[b]blackframe" -t 00:00:15.00 -y -f flv out.flv 2> out.txt
			chan_result=$?
			if [ "$chan_result" == "0" ]; then
				sound_lvl=$(cat out.txt | grep max_volume | cut -d" " -f5)
				black_dur=$(cat out.txt | grep -c blackframe)
				comp_lvl=$(ls out.flv -l | cut -d" " -f 5)
				if [ $(echo $sound_lvl" < -45 " | bc -l) == "1" ]; then
					problemFound=true
					echo Confirmed $item sound level too low - $sound_lvl dB >> problems.txt
					echo Sound issues | festival --tts
				fi
				if [ "$black_dur" -gt 300 ]; then
					problemFound=true
					echo Confirmed $item too much black frames found - $black_dur frames >> problems.txt
					echo Black picture | festival --tts
				fi
				if [ "$comp_lvl" -lt 300000 ]; then
					problemFound=true
					cp out.flv out-$(echo $item | cut -d"/" -f 4).flv
					echo Compression issues | festival --tts
					echo Confirmed $item compression too low - $comp_lvl level >> problems.txt
				fi
			else
				problemFound=true
				echo Confirmed $item produced open error >> problems.txt
			fi
			if [ "$problemFound" = true ]; then
				echo -n -e "\a"
				[ $chan_result -eq 0 ] && ffplay out.flv -autoexit -loglevel quiet
				cp out.txt out-$(echo $item | cut -d"/" -f 4).txt
				problemFound=false
			fi
		fi
		# Ovaj read je samo za hvatanje prekida
		read -t 1 -n 1 && break
	done
	read -t 1 -n 1 && break
done
