#!/bin/bash

# yum install ffmpeg v4l2-utils festival

# Pravljenje firmware-a za driver:
#   http://www.linuxtv.org/wiki/index.php/Xceive_XC3028/XC2028

#	112.25 je SNR kanal


function volLine {
	if [ "$card" == "" ]; then
		amixer -q -c 0 -- sset Line,0 unmute 2> /dev/null
		[ $? -eq 0 ] && card=0
		amixer -q -c 1 -- sset Line,0 unmute 2> /dev/null
		[ $? -eq 0 ] && card=1
	fi
	amixer -q -c $card -- sset Line,0 $1
}

chan=(
	http://46.40.5.99:8000/rts1_320
	http://46.40.5.99:8000/rts2_320
	http://46.40.5.99:8000/pink_320
	http://46.40.5.99:8000/prvatv_320
	http://46.40.5.99:8000/b92_320
	http://46.40.5.99:8000/rtv1_320
	http://46.40.5.99:8000/rtv2_320
	http://46.40.5.99:8000/fox_320
	http://46.40.5.99:8000/foxlife_320
	http://46.40.5.99:8000/mtvadria_320
	http://46.40.5.99:8000/vh1_320
	http://46.40.5.99:8000/arena_1_320
	http://46.40.5.99:8000/arena_2_320
	http://46.40.5.99:8000/arena_3_320
	http://46.40.5.99:8000/arena_4_320
	http://46.40.5.99:8000/viasat_explorer_320
	http://46.40.5.99:8000/viasat_history_320
	http://46.40.5.99:8000/davinchi_320
	http://46.40.5.99:8000/ngce_320
	http://46.40.5.99:8000/viasat_nature_320
	http://46.40.5.99:8000/travel_320
	http://46.40.5.99:8000/mgm_320
	http://46.40.5.99:8000/disney_320
	http://46.40.5.99:8000/m1_hd_320
	http://46.40.5.99:8000/m2_hd_320
	http://46.40.5.99:8000/duna_hd_320
	http://46.40.5.99:8000/duna_world_hd_320
	http://46.40.5.99:8000/tv2_320
	http://46.40.5.99:8000/rtlklub_320
	http://46.40.5.99:8000/story4_320
	http://46.40.5.99:8000/stv1_320
	http://46.40.5.99:8000/markiza_320
	http://46.40.5.99:8000/rts1_720
	http://46.40.5.99:8000/rts2_720
	http://46.40.5.99:8000/pink_720
	http://46.40.5.99:8000/prvatv_720
	http://46.40.5.99:8000/b92_720
	http://46.40.5.99:8000/rtv1_720
	http://46.40.5.99:8000/rtv2_720
	http://46.40.5.99:8000/fox_720
	http://46.40.5.99:8000/foxlife_720
	http://46.40.5.99:8000/mtvadria_720
	http://46.40.5.99:8000/vh1_720
	http://46.40.5.99:8000/arena_1_720
	http://46.40.5.99:8000/arena_2_720
	http://46.40.5.99:8000/arena_3_720
	http://46.40.5.99:8000/arena_4_720
	http://46.40.5.99:8000/viasat_explorer_720
	http://46.40.5.99:8000/viasat_history_720
	http://46.40.5.99:8000/davinchi_720
	http://46.40.5.99:8000/ngce_720
	http://46.40.5.99:8000/viasat_nature_720
	http://46.40.5.99:8000/travel_720
	http://46.40.5.99:8000/mgm_720
	http://46.40.5.99:8000/disney_720
	http://46.40.5.99:8000/m1_hd_720
	http://46.40.5.99:8000/m2_hd_720
	http://46.40.5.99:8000/duna_hd_720
	http://46.40.5.99:8000/duna_world_hd_720
	http://46.40.5.99:8000/tv2_720
	http://46.40.5.99:8000/rtlklub_720
	http://46.40.5.99:8000/story4_720
	http://46.40.5.99:8000/stv1_720
	http://46.40.5.99:8000/markiza_720
)

problemFound=false

while true
do
	for item in ${chan[*]}
	do
		echo $item
		ffmpeg -i $item -map 0:v -map 0:a:0 -af volumedetect -filter_complex "smartblur=lr=5:cr=5[a];[a]mpdecimate=max=20:frac=1:hi=768[b];[b]blackframe" -t 00:00:05.00 -y -f flv dout.flv 2> dout.txt
		chan_result=$?
		if [ "$chan_result" == "0" ]; then
			sound_lvl=$(cat dout.txt | grep max_volume | cut -d" " -f5)
			black_dur=$(cat dout.txt | grep -c blackframe)
			comp_lvl=$(ls dout.flv -l | cut -d" " -f 5)
			if [ $(echo $sound_lvl" < -40 " | bc -l) == "1" ]; then
				problemFound=true
			fi
			if [ "$black_dur" -gt 100 ]; then
				problemFound=true
			fi
			if [ "$comp_lvl" -lt 100000 ]; then
				problemFound=true
			fi
		else
			problemFound=true
		fi
		if [ "$problemFound" = true ]; then
			problemFound=false
			ffmpeg -i $item -map 0:v -map 0:a:0 -af volumedetect -filter_complex "smartblur=lr=5:cr=5[a];[a]mpdecimate=max=20:frac=1:hi=768[b];[b]blackframe" -t 00:00:05.00 -y -f flv dout.flv 2> dout.txt
			chan_result=$?
			if [ "$chan_result" == "0" ]; then
				sound_lvl=$(cat dout.txt | grep max_volume | cut -d" " -f5)
				black_dur=$(cat dout.txt | grep -c blackframe)
				comp_lvl=$(ls dout.flv -l | cut -d" " -f 5)
				if [ $(echo $sound_lvl" < -40 " | bc -l) == "1" ]; then
					problemFound=true
				fi
				if [ "$black_dur" -gt 100 ]; then
					problemFound=true
				fi
				if [ "$comp_lvl" -lt 100000 ]; then
					problemFound=true
				fi
			else
				problemFound=true
				chName=$(echo $item | cut -d/ -f 4)
				zabbix_sender -z mystique.ukljuci.ga -s $chName -k tv.result -o $chan_result > /dev/null
			fi
			if [ "$problemFound" = true ]; then
				[ $chan_result -eq 0 ] && ffplay dout.flv -autoexit -loglevel quiet
				problemFound=false
			fi
		fi

		if [ "$chan_result" == "0" ]; then		
			rm -rf result.zab
			chName=$(echo $item | cut -d/ -f 4)
			echo $chName tv.blackframes $black_dur >> result.zab
			echo $chName tv.diversity $comp_lvl >> result.zab
			echo $chName tv.result 0 >> result.zab
			echo $chName tv.sound $sound_lvl >> result.zab
			zabbix_sender -z mystique.ukljuci.ga -i result.zab > /dev/null
		fi

		read -t 1 -n 1 key
		if [ "$key" == "q" ]; then exit; fi
	done
done
