#!/bin/bash

# yum install ffmpeg v4l2-utils festival

# Pravljenje firmware-a za driver:
#   http://www.linuxtv.org/wiki/index.php/Xceive_XC3028/XC2028

#	112.25 je SNR kanal


function volLine {
	if [ "$card" == "" ]; then
		amixer -q -c 0 -- sset Line,0 unmute 2> /dev/null
		[ $? -eq 0 ] && card=0
		amixer -q -c 1 -- sset Line,0 unmute 2> /dev/null
		[ $? -eq 0 ] && card=1
	fi
	amixer -q -c $card -- sset Line,0 $1
}

chan=(
	http://localhost/dummy_tv
)

problemFound=false

while true
do
	for item in ${chan[*]}
	do
		echo $item
		ffmpeg -i $item -map 0:v -map 0:a:0 -af volumedetect -filter_complex "smartblur=lr=5:cr=5[a];[a]mpdecimate=max=20:frac=1:hi=768[b];[b]blackframe" -t 00:00:05.00 -y -f flv dout.flv 2> dout.txt
		chan_result=$?
		if [ "$chan_result" == "0" ]; then
			sound_lvl=$(cat dout.txt | grep max_volume | cut -d" " -f5)
			black_dur=$(cat dout.txt | grep -c blackframe)
			comp_lvl=$(ls dout.flv -l | cut -d" " -f 5)
			if [ $(echo $sound_lvl" < -40 " | bc -l) == "1" ]; then
				problemFound=true
			fi
			if [ "$black_dur" -gt 100 ]; then
				problemFound=true
			fi
			if [ "$comp_lvl" -lt 100000 ]; then
				problemFound=true
			fi
		else
			problemFound=true
		fi
		if [ "$problemFound" = true ]; then
			problemFound=false
			ffmpeg -i $item -map 0:v -map 0:a:0 -af volumedetect -filter_complex "smartblur=lr=5:cr=5[a];[a]mpdecimate=max=20:frac=1:hi=768[b];[b]blackframe" -t 00:00:05.00 -y -f flv dout.flv 2> dout.txt
			chan_result=$?
			if [ "$chan_result" == "0" ]; then
				sound_lvl=$(cat dout.txt | grep max_volume | cut -d" " -f5)
				black_dur=$(cat dout.txt | grep -c blackframe)
				comp_lvl=$(ls dout.flv -l | cut -d" " -f 5)
				if [ $(echo $sound_lvl" < -40 " | bc -l) == "1" ]; then
					problemFound=true
				fi
				if [ "$black_dur" -gt 100 ]; then
					problemFound=true
				fi
				if [ "$comp_lvl" -lt 100000 ]; then
					problemFound=true
				fi
			else
				problemFound=true
				chName=$(echo $item | cut -d/ -f 4)
				zabbix_sender -z localhost -s $chName -k tv.result -o $chan_result > /dev/null
			fi
			if [ "$problemFound" = true ]; then
				[ $chan_result -eq 0 ] && ffplay dout.flv -autoexit -loglevel quiet
				problemFound=false
			fi
		fi

		if [ "$chan_result" == "0" ]; then		
			rm -rf result.zab
			chName=$(echo $item | cut -d/ -f 4)
			echo $chName tv.blackframes $black_dur >> result.zab
			echo $chName tv.diversity $comp_lvl >> result.zab
			echo $chName tv.result 0 >> result.zab
			echo $chName tv.sound $sound_lvl >> result.zab
			zabbix_sender -z localhost -i result.zab > /dev/null
		fi

		read -t 1 -n 1 key
		if [ "$key" == "q" ]; then exit; fi
	done
done
